parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#    App\Handler\CreateUserHandler:
#        tags:
#            - { name: command_handler, handles: App\Command\CreateUser }
